#!/usr/bin/env bash
# script to transfer files from client to server

if [ $# -lt 3 ]
then
	echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
else
	echo 'correct arg'
	path_file=$1
	ip_server=$2
	username=$3
	key_path=$4

	scp -o 'StrictHostKeyChecking accept-new' -i "$key_path" "$path_file" "$username"@"$ip_server":~/

fi
